ls_debug: 
	gcc ls.c -o ls -D DEBUG -Wall
ls_run:
	gcc ls.c -o ls -Wall
touch_debug: 
	gcc touch.c -o touch -D DEBUG -Wall
touch_run:
	gcc touch.c -o touch -Wall
mkdir_debug: 
	gcc mkdir.c -o mkdir -D DEBUG -Wall
mkdir_run:
	gcc mkdir.c -o mkdir -Wall
cp_debug: 
	gcc cp.c -o cp -D DEBUG -Wall
cp_run:
	gcc cp.c -o cp -Wall